services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "1400:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylist-network

  mylist-server:
    build:
      context: ./MyList.Server
    container_name: mylist-server
    restart: always
    networks:
      - mylist-network
    volumes:
      - ./data/mylist.db:/app/mylist.db
    # ports:
    #   - "8080:8080"  # Expose the app's port if needed for local dev

  mylist-client:
    build:
      context: ./mylist.client
    container_name: mylist-client
    restart: always
    networks:
      - mylist-network
    # ports:
    #   - "3000:3000"  # Expose the app's port if needed for local dev

  mylist-search-engine:
    build:
      context: ./mylist.search-engine
    container_name: mylist-search-engine
    restart: always
    networks:
      - mylist-network
    volumes:
      - ./data/mylist.db:/app/mylist.db
    # ports:
    #   - "8080:8080"  # Expose the app's port if needed for local dev

networks:
  mylist-network:
    driver: bridge
